---

- name: Enable Canonical partners repository
  ansible.builtin.apt_repository:
    repo: '{{ item }} http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner'
    state: present
  become: '{{ do_become }}'
  loop:
    - deb
    - deb-src
  tags: [desktop, config]
  when: ansible_distribution == 'Ubuntu'

- block:
    - name: Install Ubuntu base packages
      ansible.builtin.package:
        name: '{{ ubuntu_base_packages }}'
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Ubuntu desktop packages
      ansible.builtin.package:
        name: '{{ ubuntu_desktop_packages }}'
        state: present
      when: desktop_package == 'ubuntu-desktop'

    - name: Install office packages
      ansible.builtin.package:
        name: '{{ office_packages }}'
        state: present

    - name: Install system packages
      ansible.builtin.package:
        name: '{{ system_packages }}'
        state: present

    - name: Update apt-file cache
      ansible.builtin.command:
        apt-file update
      when: "ansible_pkg_mgr == 'apt'"

    - name: Remove bumblebee packages
      ansible.builtin.package:
        name:
          - bumblebee
          - bumblebee-nvidia
        state: absent

    - name: Install files utilities packages
      ansible.builtin.package:
        name: '{{ file_utility_packages }}'
        state: present

    - name: Install miscellaneous packages
      ansible.builtin.package:
        name: '{{ miscellaneous_packages }}'
        state: present

    - name: Install virtualization packages
      ansible.builtin.package:
        name: '{{ virtualization_packages }}'
        state: present

    - name: Install web packages
      ansible.builtin.package:
        name: '{{ web_packages }}'
        state: present
  become: '{{ do_become }}'
  tags: [desktop, packages]

...
