---
# FIXME tags must be repeated in included files https://github.com/ansible/ansible/issues/16985

- block:
    - name: Remove snap packages
      ansible.builtin.command: >
        snap remove --purge {{ item }}
      loop: '{{ desktop_snap_flush_packages }}'
      failed_when: false

    - name: Install Mozilla Team apt repository
      ansible.builtin.apt_repository:
        repo: ppa:mozillateam/ppa
        filename: ansible_roles_desktop_mozillateam
        state: present

    - name: Set apt preferences for no-snap Firefox
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/mozilla
        content: |
          Package: *
          Pin: release o=LP-PPA-mozillateam
          Pin-Priority: 500

          Package: firefox*
          Pin: release o=Ubuntu
          Pin-Priority: -1

          Package: thunderbird
          Pin: version 2:1snap*
          Pin-Priority: -1

    - name: Set apt preferences for no-snap Chromium
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/chromium
        content: |
          Package: chromium*
          Pin: origin "deb.debian.org"
          Pin-Priority: 700
  become: '{{ do_become }}'
  tags: [desktop, packages]

...
